### ISSUE TITLE
Resolve Adobe Commerce Cloud security report/warning

### ISSUE THREAD

**Issue by dbashyal** [markshust/magento2-module-disabletwofactorauth#26]
Status: fail 
Group: Cloud Backend
Scan Name: 2FA Modules 
Scan Details: Mandatory two-factor authentication modules are enabled. Modules from the list must be deleted: 
- 'MarkShust_DisableTwoFactorAuth'.

How to stop getting this alert when using this module?

**Comment by markshust** [comment]
Thanks @dbashyal for this report.

To get around this, we are going to urge everyone to install this as a dev dependency with `composer require --dev`. You can also change where this appears in your `composer.json` file, moving it from the `require` property to `require-dev`.

Since Adobe Commerce runs `composer install --no-dev`, it will bypass these dev modules which should prevent the security report from flagging this as a concern.

I'm working on a fix and updated documentation, and will release a new version for this later today 👍

**Comment by markshust** [comment]
I also found out about this Composer feature: https://github.com/composer/composer/pull/10960

When the `dev` keyword is added to the list of keywords in the `composer.json` file, it will automatically suggest it to be a dev dependency, and flag a warning if the `--dev` flag is not passed in. This is a good addition to prevent this issue from occurring 👍

**Comment by markshust** [comment]
PR merged in and will momentarily tag a new release to fix.

**Comment by dbashyal** [comment]
@markshust 

That didn't help. 
![image](https://github.com/user-attachments/assets/040a264b-1d00-4396-b27c-f1a746eb08bd)

>> Since Adobe Commerce runs `composer install --no-dev`, it will bypass these dev modules which should prevent the security report from flagging this as a concern.

FYI - it includes require-dev modules as well.
![image](https://github.com/user-attachments/assets/97c43803-5c18-4a4c-8bbd-fe4f18e67240)

**Comment by markshust** [comment]
Perhaps this is related to this ticket, which I chimed in on 7 weeks ago: https://github.com/magento/magento-cloud/pull/534

But this ticket has been opened with them for more than 2 years, and has still not been merged in yet. Please feel free to chime in there and create a ruckus.

This ticket is resolved on my end, so this is falling back to Adobe now as it's all resolved. Since they are preventing my valid modules from being installed on their cloud service, I do not recommend using Adobe Cloud. There are many other great providers out there like Nexcess, Webscale's Stratus, and luroConnect.
